federation_version: =2.11.3

subgraphs:
  user:
    routing_url: http://user-service:8081/graphql
    schema:
      file: ../user-service/src/main/resources/graphql/schema.graphqls
  booking:
    routing_url: http://booking-service:8082/graphql
    schema:
      file: ../booking-service/src/main/resources/graphql/schema.graphqls
